name: Fetching Company Info PROD

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: 0 17 * * 0 # 00:00 PM in Vietnam

jobs:
  fetch-data:
    runs-on: ubuntu-24.04
    environment: secrets
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          ref: master # checkout master branch

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install uv
        run: |
          pip install uv

      - name: install dependencies with uv
        run: |
          uv sync --frozen

      - name: fetch company info
        run: |
          cd src
          uv run python gcompany-info.py

      - name: notify telegram private group
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          cd src
          uv run python notification-overview.py

      - name: get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: push changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          message: Updated company overview at ${{ env.date }}
          email: action@github.com
          name: GitHub Action
